import React from 'react';

function App() {

  const [clients, setClientes] = React.useState([
    {"id":"1","name":"3A Tecnologia","description":"O site traz aspectos institucionais, mas procurar apresentar com detalhes as caracter\u00edsticas dos produtos.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/3a.png"},
  {"id":"2","name":"AABB Recife","description":"Portal com diversas informa\u00e7\u00f5es sobre as atividades do Clube. H\u00e1 no portal uma \u00e1rea exclusiva para o associado, contendo como principal fun\u00e7\u00e3o a impress\u00e3o do boleto da mensalidade.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/aabb.png"},
  {"id":"3","name":"ABCC","description":"Site da ABCC com informa\u00e7\u00f5es da entidade, seus projetos e as mat\u00e9rias publicadas na revista da Associa\u00e7\u00e3o. Al\u00e9m do site, j\u00e1 foram desenvolvidas alguns sistemas: patrim\u00f4nio,financeiro e aulas.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/abcc.png"},
  {"id":"346","name":"Ackta Tecnologia","description":"Desenvolvimento do site da Ackta, empresa de tecnologia de SP","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/ackta.png"},
  {"id":"306","name":"ACP","description":"Site da empresa, com banco de dados e ZaitePronto","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/acp.png"},
  {"id":"76","name":"ADE Brasil","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/adeBrasil.png"},
  {"id":"367","name":"Ademi-PE","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/ademipe.png"},
  {"id":"77","name":"Adm Empresarial","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/admEmpresarial.png"},
  {"id":"378","name":"Adrena Bike","description":"Site da loja Adrena Bike, com pedido eletr\u00f4nico","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"357","name":"Adrianinha Basquetebol","description":"Site do projeto de escolinhas Adrianinha Basquetebol","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/adrianinha.png"},
  {"id":"78","name":"ADVB-PE","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/advbpe.png"},
  {"id":"327","name":"AGS","description":"Site da empresa, com se\u00e7\u00f5es institucionais e \u00e1rea para pedido de produtos","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/ags.png"},
  {"id":"79","name":"Alarm Center","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/alarmcenter.png"},
  {"id":"80","name":"Albuquerque Pinto","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/albuquerquePinto.png"},
  {"id":"352","name":"All 4 Kids School","description":"Site da escola All 4 Kids","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/all4kids.png"},
  {"id":"81","name":"Alouer","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/alouer.png"},
  {"id":"82","name":"Alternativa","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"83","name":"Alumina Esquadrias","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/alumina.png"},
  {"id":"84","name":"Amelle","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/amelle.png"},
  {"id":"356","name":"Amigos da Igreja","description":"App e site para a comunidade de paroquianos adquirir servi\u00e7os e produtos pertencentes ao projeto.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/amigosdaigreja.png"},
  {"id":"319","name":"\u00c2ncora Imobili\u00e1ria","description":"Redes sociais (facebook e instagran) para divulga\u00e7\u00e3o da imobili\u00e1ria e dos im\u00f3veis dispon\u00edveis.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/ancora.png"},
  {"id":"85","name":"Answ.me","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"86","name":"Antonio de Carlo","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"87","name":"Arclima Engenharia","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/arclima.png"},
  {"id":"88","name":"Arcoduto","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/arcoduto.png"},
  {"id":"48","name":"ARPE","description":"Portal da entidade com diversas informa\u00e7\u00f5es institucionais e not\u00edcias","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/arpe.png"},
  {"id":"390","name":"Arqueatec","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"89","name":"Arquitetos Brasil","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/arquitetosBrasil.png"},
  {"id":"347","name":"Arte L\u00ea","description":"Sistema para gest\u00e3o dos alunos e suas aquisi\u00e7\u00f5es em servi\u00e7os como excurs\u00e3o e esportes","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"348","name":"Artfex Cadeiras","description":"Site institucional da empresa produtora de cadeiras para casa de eventos.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/artfex.png"},
  {"id":"90","name":"Artgo","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"91","name":"ASA Industria","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/asa.png"},
  {"id":"4","name":"ASD Inform\u00e1tica","description":"Site da ASD, com informa\u00e7\u00f5es institucionais, servi\u00e7os e produtos.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/asd.png"},
  {"id":"5","name":"ASPJ-PE","description":"Portal da ASPJ, com not\u00edcias e demais informa\u00e7\u00f5es para o associado. H\u00e1 uma ferramenta de classificados para o associado. ","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/aspj.png"},
  {"id":"6","name":"ASSERPE","description":"Portal com informa\u00e7\u00f5es e not\u00edcias sobre a associa\u00e7\u00e3o, contendo fotos, v\u00eddeos, downloads, etc. ","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/asserpe.png"},
  {"id":"92","name":"Astral Cadernos","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/astralCadernos.png"},
  {"id":"93","name":"Asyst","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"94","name":"Atlantis Importadora","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/atlantis.png"},
  {"id":"345","name":"Azov","description":"Site da empresa apresentado os produtos novos e seminovos dispon\u00edveis.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/azov.png"},
  {"id":"359","name":"Bello Frio","description":"Site da empresa de manuten\u00e7\u00e3o de ar-condiconado, apresentando os seus servi\u00e7os, clientes e outros","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/belloFrio.png"},
  {"id":"364","name":"Berlitz","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/berlitz.png"},
  {"id":"95","name":"BestWay","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/bestway.png"},
  {"id":"49","name":"Betel","description":"Desenvolvemos um sistema para o registro e acompanhamento do pedido","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/betel.png"},
  {"id":"96","name":"Bianco Quiaro","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"97","name":"Bio Fair Trade","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/biofair.png"},
  {"id":"98","name":"Bombeiros","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/bombeiros.png"},
  {"id":"99","name":"Bonde Amigo ","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"7","name":"Borba Consultoria","description":"Site que pretende funcionar como um portal de not\u00edcias sobre a \u00e1rea de atua\u00e7\u00e3o.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/borba.png"},
  {"id":"66","name":"Borba Consultoria","description":"Site com a hist\u00f3ria do movimento que ocorreu na d\u00e9cada de 90.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"100","name":"Brasil na WEB","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"101","name":"Braziliam Gypsum","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"102","name":"Broomer","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/broomer.png"},
  {"id":"103","name":"Cabo","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/cabo.png"},
  {"id":"300","name":"Cala\u00e7a Advogados","description":"Site da empresa, com banco de dados e ZaitePronto","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/calaca.png"},
  {"id":"104","name":"Canizzaro","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"11","name":"Capital Factoring","description":"Site institucional, com a apresenta\u00e7\u00e3o da empresa e de seus servi\u00e7os. O site tamb\u00e9m conta com uma ferramenta de inser\u00e7\u00e3o de border\u00f4s.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/capital.png"},
  {"id":"350","name":"Carlos Queiroz Advogados","description":"Site do escrit\u00f3rio de advocacia, com informa\u00e7\u00f5es institucionais e extranet.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/carlosQueiroz.png"},
  {"id":"105","name":"Carmem","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"380","name":"Carneiros Temporada","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/Carneiros.jpg"},
  {"id":"50","name":"Cartruck Ve\u00edculos","description":"Site institucional com divulga\u00e7\u00e3o dos ve\u00edculos dispon\u00edveis para venda","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/cartruck.png"},
  {"id":"106","name":"Carvalho e Lopes","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/carvalhoLopes.png"},
  {"id":"334","name":"Casa Grande Engenharia","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"107","name":"CasaAlta","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/casaAlta.png"},
  {"id":"12","name":"Casimper","description":"Site institucional que tem a necessidade de tamb\u00e9m se tornar um site vendedor.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/casimper.png"},
  {"id":"13","name":"Castro Neves Construtora","description":"Site institucional com informa\u00e7\u00f5es da empresa, not\u00edcias e portf\u00f3lio. Quando h\u00e1 um novo empreendimento, h\u00e1 a tabela de pre\u00e7os e fotos da obra.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/castroNeves.png"},
  {"id":"14","name":"CAT Consultoria","description":"Site institucional com informa\u00e7\u00f5es e not\u00edcias sobre o mercado financeiro e sobre empreendedorismo, divulga seus cursos atrav\u00e9s do site. ","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/catConsultoria.png"},
  {"id":"108","name":"CB Pneus","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"374","name":"CBIC","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"109","name":"CCB-UFPE","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/ccb.png"},
  {"id":"110","name":"Centavos da Sorte","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/centavos.png"},
  {"id":"111","name":"Center Telecom","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"379","name":"Ceplan Consultoria","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/logo_Ceplan.png"},
  {"id":"51","name":"CERE","description":"Site da entidade com divulga\u00e7\u00e3o dos cursos dispon\u00edveis","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/cere.png"},
  {"id":"294","name":"CHDI","description":"Site da entidade, com banco de dados e ZaitePronto","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/chdi.png"},
  {"id":"112","name":"Chico Amorim","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"15","name":"CHSZ","description":"O site serve para divulgar o espa\u00e7o e tamb\u00e9m para informar feitos dos alunos em competi\u00e7\u00f5es locais e nacionais.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/chzs.png"},
  {"id":"16","name":"Cia Consultores","description":"O site traz informa\u00e7\u00f5es institucionais, com divulga\u00e7\u00e3o de servi\u00e7os e cursos.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/ciaConsultores.png"},
  {"id":"113","name":"Cia do Futebol","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/ciaFutebol.png"},
  {"id":"114","name":"Cicero","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"115","name":"Cin-Fiepe","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/cin.png"},
  {"id":"17","name":"Circuito Hipismo","description":"O Circuito Norte Nordeste de Hipismo possui portal que disponibiliza diversas informa\u00e7\u00f5es, n\u00e3o s\u00f3 sobre o circuito, mas sobre as novidades do hipismo no Brasil.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/circuito.png"},
  {"id":"290","name":"Circulo Design","description":"Site institucional com servi\u00e7os, portfolio e v\u00e1rias informa\u00e7\u00f5es","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/circulodesign.png"},
  {"id":"117","name":"CIV","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/civ.png"},
  {"id":"391","name":"Class Match","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/ClassMatch.us02.png"},
  {"id":"118","name":"Clementina Duarte","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"119","name":"Clipemania","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"120","name":"Clube de Compras","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"289","name":"Col\u00e9gio Santa Maria","description":"Site institucional com informa\u00e7\u00f5es do Col\u00e9gio, not\u00edcias.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/santaMaria.png"},
  {"id":"8","name":"Compliance","description":"Site institucional","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/compliance.png"},
  {"id":"121","name":"Concept","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"387","name":"Condecora","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/Condecora.jpg"},
  {"id":"122","name":"Consumint","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"385","name":"Continentes Consultoria","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/logo_continentes.png"},
  {"id":"123","name":"Cooptec","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/cooptec.png"},
  {"id":"124","name":"Copeo","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/copeo.png"},
  {"id":"349","name":"CR3","description":"Site institucional da CR3, com informa\u00e7\u00f5es da empresa, \u00e1rea para cursos e extranet.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/cr3.png"},
  {"id":"373","name":"CRO-PE","description":"ZAP","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"125","name":"Cyberland","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/cyberland.png"},
  {"id":"126","name":"Da FCap","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"320","name":"Dali Cocina","description":"Site do restaurante","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/dali.png"},
  {"id":"127","name":"Dantas Empresarial","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/dantas.png"},
  {"id":"128","name":"Delega\u00e7\u00e3o Holandesa","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"314","name":"DG Tecnologia","description":"Site da empresa onde constam os produtos e servi\u00e7os oferecidos pela mesma, com banco de dados e ZaitePronto.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/dg.png"},
  {"id":"129","name":"Diacolor","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/diacolor.png"},
  {"id":"383","name":"Diet Food","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/DietFood.jpg"},
  {"id":"130","name":"Dilson Luz","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"131","name":"DIP","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/dip.png"},
  {"id":"132","name":"Diseno-classificautos","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"20","name":"DIX Neg\u00f3cios","description":"Sistema para registro e controle das vendas e comiss\u00f5es.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/dix.png"},
  {"id":"371","name":"DKatz Construtora","description":"Site da Construtora","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/dkatz.png"},
  {"id":"52","name":"DocMaster","description":"Site institucional","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"133","name":"Dolce Vitrine","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/dolceVitrine.png"},
  {"id":"134","name":"Duarte","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/duarte.png"},
  {"id":"369","name":"E Vai Rolar A Festa","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/logo_evairolarafesta.png"},
  {"id":"135","name":"Eclipse Transportadora","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/eclipse.png"},
  {"id":"136","name":"Ecoflora","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/ecoflora.png"},
  {"id":"137","name":"Eduardo and Katie","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"53","name":"EduardoMartins","description":"Site institucional dom informa\u00e7\u00f5es dos servi\u00e7os e das obras j\u00e1 realizadas","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/eduardoMartins.png"},
  {"id":"138","name":"Eletron","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/eletron.png"},
  {"id":"354","name":"Elijah Campelo","description":"Site do escrit\u00f3rio de advocacia Elijah Campelo","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/elijah.png"},
  {"id":"139","name":"Eloplast","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/eloplast.png"},
  {"id":"140","name":"Embriocon","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"142","name":"ENAU","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"143","name":"Encruzilhada Pneus","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"18","name":"EnergiaNE","description":"O site traz informa\u00e7\u00f5es institucionais, com divulga\u00e7\u00e3o de servi\u00e7os, leil\u00f5es, legisla\u00e7\u00e3o e not\u00edcias.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/traderenergiaNE.png"},
  {"id":"144","name":"Engenharia Produ\u00e7\u00e3o - UFPE","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/engProd_cdsid.png"},
  {"id":"71","name":"ESC Engenharia","description":"Site da empresa com informa\u00e7\u00f5es institucionais.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/escEng.png"},
  {"id":"317","name":"Escola Bem Me Quer","description":"Site da Escola Bem-Me-Quer com informa\u00e7\u00f5es institucionais sobre as novidades e atividades da escola, dando acesso aos pais e respons\u00e1veis dos alunos.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/escolabemmequer.png"},
  {"id":"377","name":"Escola Conecta","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"145","name":"Esmape","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/esmape.png"},
  {"id":"146","name":"Estructural","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/estructural.png"},
  {"id":"324","name":"Est\u00fadio P\u00e1ssaro","description":"Site do est\u00fadio com os tipos de trabalhos que podem ser desenvolvidos.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/estudiopassaro.png"},
  {"id":"147","name":"Eteno","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/eteno.png"},
  {"id":"148","name":"Etronab","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"28","name":"Eurovia Nissan","description":"Site da concession\u00e1ria, com disposi\u00e7\u00e3o dos ve\u00edculos dispon\u00edveis, promo\u00e7\u00f5es e servi\u00e7os.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/grupo_vs_eurovia_nissan.png"},
  {"id":"27","name":"Eurovia Renault","description":"Site da concession\u00e1ria, com disposi\u00e7\u00e3o dos ve\u00edculos dispon\u00edveis, promo\u00e7\u00f5es e servi\u00e7os.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/grupo_vs_eurovia_renault.png"},
  {"id":"21","name":"Excelsior Seguros","description":"O site traz informa\u00e7\u00f5es da empresa, produtos e not\u00edcias da \u00e1rea de atua\u00e7\u00e3o. H\u00e1 uma Extranet, bastante utilizada pelos corretores de seguro.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/excelsior.png"},
  {"id":"318","name":"Expojunina","description":"Site do evento realizado em Gravat\u00e1","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"150","name":"Express","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"22","name":"Facho ","description":"O site da FACHO funciona como um portal para alunos e empregados da institui\u00e7\u00e3o. O site est\u00e1 estruturado por \u00e1rea de ensino, inclusive o Zaite Pronto obedece essa ordena\u00e7\u00e3o. A Zaite semestralmente trabalha bastante com o vestibular, desde a inscri\u00e7\u00e3o com pagamento at\u00e9 a prova on-line.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/facho.png"},
  {"id":"361","name":"Facilita","description":"Sistema para gerenciar os atendimentos feitos aos clientes da empresa, com registros dos status dos documentos necess\u00e1rios para casa pedido.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/facilita.png"},
  {"id":"72","name":"Faculdade Guararapes","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/faculdadeguararapes.png"},
  {"id":"151","name":"Falcao","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"152","name":"Farina Ventrilho","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/farina.png"},
  {"id":"153","name":"Farm\u00e1cias Independente","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/farmaciaIndependente.png"},
  {"id":"154","name":"FarmaForte","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"155","name":"Fernando Campos","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"156","name":"Ferreira Pinto","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/ferreiraPinto.png"},
  {"id":"311","name":"Festa Cheia","description":"Projeto Festa Cheia para divulga\u00e7\u00e3o e venda de eventos diversos","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"157","name":"Festival de Cinema","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/festivalcinema.png"},
  {"id":"158","name":"FIEC","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"381","name":"Filig","description":"Site do evento da edi\u00e7\u00e3o 2022","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/Filig.jpg"},
  {"id":"375","name":"Filiservice","description":"Site da empresa com divulga\u00e7\u00e3o dos produtos","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/Filiservice.jpg"},
  {"id":"159","name":"FlorArte","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/florarte.png"},
  {"id":"315","name":"FMU","description":"Site da faculdade, com banco de dados e ZaitePronto","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/fmu.png"},
  {"id":"160","name":"Freire Advogados","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/freire.png"},
  {"id":"337","name":"Futebol Conectado","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/fpf_futebolconectado.png"},
  {"id":"23","name":"Game Station","description":"Sistema para registro e gerenciamento das festas de anivers\u00e1rio de todas as unidades da empresa","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/gameStation.png"},
  {"id":"161","name":"Game Station Buffet","description":"Sistema para registro e gerenciamento da vendas de festas da empresa","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/gameStationBuffet.png"},
  {"id":"326","name":"GAP Cursos","description":"Site da institui\u00e7\u00e3o com informa\u00e7\u00f5es sobre os cursos al\u00e9m de uma \u00e1rea para os alunos e pais.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/gap.png"},
  {"id":"162","name":"GEF","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"54","name":"Geosistemas Engenharia","description":"Site da empresa com informa\u00e7\u00f5es institucionais e sistema de gerenciamento financeiro e de patrim\u00f4nio","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/geosistemas.png"},
  {"id":"163","name":"Geraldo Freire","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"164","name":"GERE","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"303","name":"GGTI","description":"Site da empresa, com banco de dados e ZaitePronto","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/ggti.png"},
  {"id":"24","name":"Gikatz Construtora","description":"Site institucional com informa\u00e7\u00f5es da empresa, not\u00edcias e portf\u00f3lio. Quando h\u00e1 um novo empreendimento, h\u00e1 a tabela de pre\u00e7os e fotos da obra.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/gikatz.png"},
  {"id":"29","name":"Granvia","description":"Site da concession\u00e1ria, com disposi\u00e7\u00e3o dos ve\u00edculos dispon\u00edveis, promo\u00e7\u00f5es e servi\u00e7os.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/grupo_vs_granvia.png"},
  {"id":"165","name":"Gr\u00e3o Design","description":"Site do escrit\u00f3rio de design com atua\u00e7\u00e3o em SP.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/graoDesign.png"},
  {"id":"25","name":"Grupo Atento","description":"Site institucional para mostrar servi\u00e7os realizados pela empresa, al\u00e9m de noticias sobre a empresa, acontecimentos na empresa. ","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"166","name":"Grupo CM","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"342","name":"Grupo DHS","description":"Sistema de gest\u00e3o de atendimentos","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/grupoDHS.png"},
  {"id":"167","name":"Grupo Santa Rosa","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"321","name":"Grupo Torcida","description":"Site de empresa de comunica\u00e7\u00e3o esportiva, cujo principais produtos s\u00e3o o \"Jornal Torcida\" e a \"Revista Torcida\".","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/grupotorcida.png"},
  {"id":"70","name":"Grupo ViaSul","description":"Criar a p\u00e1gina geral do Grupo, com o dom\u00ednio grupoviasul.com. A p\u00e1gina deve conter todas as marcas (com o acesso por cidade), assim como tem-se na da Eurovia. Em todos os sites tem a barra com os endere\u00e7os, mas como n\u00e3o tem como colocar todos endere\u00e7os\/telefones logo de cara, pode-se pensar na melhor forma de incluir isso ou pode-se simplesmente n\u00e3o colocar. ","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"360","name":"Guimar\u00e3es Ferreira","description":"Site da Guimar\u00e3es Ferreira, feito em parceira com a Koa","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/guimferreira.png"},
  {"id":"168","name":"Hagua Comunica\u00e7\u00e3o","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/hagua.png"},
  {"id":"353","name":"HBR Engenharia","description":"Site institucional da empresa HBR Engenharia","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/hbr.png"},
  {"id":"75","name":"HG Code","description":"Site institucional com informa\u00e7\u00f5es sobre a empresa, produtos, servi\u00e7os, not\u00edcias, cases, certificados e parceiros da empresa.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/hgcode.png"},
  {"id":"169","name":"Higiene","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"170","name":"Hosp Especial","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/hospitalEspecial.png"},
  {"id":"171","name":"Hotel Tivoli","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"55","name":"HSM","description":"Aplicativo no Face para inscri\u00e7\u00e3o de estudantes, com a participa\u00e7\u00e3o numa enquete.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/hsm.png"},
  {"id":"172","name":"I3R","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/i3r.png"},
  {"id":"173","name":"Ilha de Itamarac\u00e1","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/ilhadeitamaraca.png"},
  {"id":"325","name":"Ilustra Tha\u00eds","description":"Site da artista com os tipos de trabalhos que podem ser desenvolvidos.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/ilustrathais.png"},
  {"id":"31","name":"Imel","description":"Site institucional, com informa\u00e7\u00f5es da empresa e not\u00edcias sobre novidades relacionadas a energia brasileira. ","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/imel.png"},
  {"id":"56","name":"Impermaster","description":"Site institucional, com divulga\u00e7\u00e3o dos produtos e servi\u00e7os","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"174","name":"Impulso","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/impulso.png"},
  {"id":"175","name":"Innovative","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"339","name":"Instituto Ecos","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"176","name":"Intercambio-com","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"177","name":"Intercom","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"30","name":"Intervia Kia","description":"Site da concession\u00e1ria, com disposi\u00e7\u00e3o dos ve\u00edculos dispon\u00edveis, promo\u00e7\u00f5es e servi\u00e7os.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/grupo_vs_intervia.png"},
  {"id":"333","name":"Italiana","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"363","name":"J Cavalcanti","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/JCavalcanti.png"},
  {"id":"178","name":"JBL Nordeste","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"141","name":"JMA - EMentoring","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/ementoring.png"},
  {"id":"179","name":"Jo\u00e3o Paulo 13","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"180","name":"Joao Santos Nassau","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"365","name":"Jornal O Poder","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/jornalOpoder.png"},
  {"id":"181","name":"Josemin Voxweb","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"182","name":"JP Lemos","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/jp.png"},
  {"id":"68","name":"Jupiter Comunica\u00e7\u00e3o","description":"Cria\u00e7\u00e3o do site com banco de talentos e prepara\u00e7\u00e3o do zp!.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/jupiter.png"},
  {"id":"183","name":"Jynx","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"184","name":"K2 Host","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"185","name":"Kacil","description":"Site da empresa, com banco de dados e ZaitePronto","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/kacil.png"},
  {"id":"36","name":"Kronnus","description":"Site institucional simples, mostra os produtos da empresa, mas n\u00e3o tem a inten\u00e7\u00e3o de funcionar como loja virtual. \u00c9 meramente uma vitrine. ","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/n3_kronnus.png"},
  {"id":"32","name":"Kronorte","description":"Site institucional com informa\u00e7\u00f5es sobre os produtos da empresa. H\u00e1 vers\u00f5es do site em ingl\u00eas e em espanhol. Tamb\u00e9m h\u00e1 um sistema bem espec\u00edfico para gera\u00e7\u00e3o de pedidos e propostas.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/kronorte.png"},
  {"id":"186","name":"Laborat\u00f3rio de Letras","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"187","name":"Laureano Filho","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"188","name":"Lazer","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"189","name":"LBR","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/lbr.png"},
  {"id":"389","name":"Liame","description":"Site da empresa, para divulga\u00e7\u00e3o do curso","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"190","name":"Light Design","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/lightDesign.png"},
  {"id":"69","name":"Lote Certo","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"191","name":"LucVest","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"192","name":"Lya","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"196","name":"M Ara\u00fajo","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/maraujo.png"},
  {"id":"193","name":"Machado Guimar\u00e3es","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/machadoGuimaraes.png"},
  {"id":"194","name":"Mack Express","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/mack.png"},
  {"id":"297","name":"Makplan","description":"Site da empresa, com banco de dados e ZaitePronto","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/makplan.png"},
  {"id":"305","name":"Makplan","description":"Sistema para divulga\u00e7\u00e3o de feir\u00f5es promovidos pelo Santander (e outros bancos) e inscri\u00e7\u00e3o no feir\u00e3o pelos lojistas.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"343","name":"Marcelo Falc\u00e3o","description":"Site do dentista com informa\u00e7\u00f5es da \u00e1rea de atua\u00e7\u00e3o","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"197","name":"Marcos Jair","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"198","name":"Maria Iluminada","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/mariaIluminada.png"},
  {"id":"355","name":"Marolla Guedes","description":"Site do Fot\u00f3grafo Marolla Guedes","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"199","name":"Meira Ramos","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"200","name":"Memoria Grafica","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/memoriaGrafica.png"},
  {"id":"384","name":"Mercado 3E","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/Solar.jpg"},
  {"id":"57","name":"Meteora","description":"Site institucional com divulga\u00e7\u00e3o dos servi\u00e7os, pacotes e tarifas.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/meteora.png"},
  {"id":"201","name":"Metropolitan","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"33","name":"Midas C\u00e2mbio","description":"Sistema que registra as opera\u00e7\u00f5es realizadas pela empresa, Posteriormente foi feito um site institucional com informa\u00e7\u00f5es da empresa e not\u00edcias da \u00e1rea de atua\u00e7\u00e3o. ","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/midas.png"},
  {"id":"34","name":"MidiaVox","description":"Site institucional com informa\u00e7\u00f5es da empresa, servi\u00e7os, produtos e not\u00edcias da \u00e1rea de atua\u00e7\u00e3o. Tamb\u00e9m h\u00e1 uma Intranet.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/midiavox.png"},
  {"id":"202","name":"Mira Filmes","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/miraFilmes.png"},
  {"id":"203","name":"Miriam","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"204","name":"Mix","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"304","name":"Monsueto","description":"Facebook para se divulgar como profissional: Advogada Trabalhista e Professora. ","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"205","name":"Monsu\u00eato Advogados","description":"Site do escrit\u00f3rio de advocacia, com informa\u00e7\u00f5es institucionais, not\u00edcias e eventos da \u00e1rea.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/monsueto.png"},
  {"id":"206","name":"Moveis Arruda","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/moveisArruda.png"},
  {"id":"344","name":"Movimento Cidade Melhor","description":"Sites de pol\u00edticos e movimentos","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"310","name":"Movimento Vida Sustent\u00e1vel","description":"Site focado na sustentabilidade. Institui\u00e7\u00e3o que divulga seus cursos, f\u00f3runs e semin\u00e1rios. Al\u00e9m de falar sobre diversos assuntos ligados a sustentabilidade. ","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/movimentovidasustentavel.png"},
  {"id":"336","name":"Mr Plot","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"207","name":"Muca","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"208","name":"Multiave","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/multiave.png"},
  {"id":"209","name":"Multicorp","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/multicorp.png"},
  {"id":"338","name":"My Pet","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/mypet.png"},
  {"id":"35","name":"N3 Computadores","description":"Site com informa\u00e7\u00f5es sobre os produtos da N3, com diversas informa\u00e7\u00f5es t\u00e9cnicas. Entretanto o site deve se tornar mais \u201cvendedor\u201d.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/n3.png"},
  {"id":"372","name":"Natural da Vaca","description":"Hotsite SAC","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/natural_da_vaca.png"},
  {"id":"58","name":"Nautico","description":"Portal do Clube N\u00e1utico Capibaribe com diversas informa\u00e7\u00f5es sobre o clube, a gest\u00e3o, e futebol, como o elenco e a comiss\u00e3o t\u00e9cnica, por exemplo.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/nautico.png"},
  {"id":"210","name":"Negroove","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"211","name":"Newsupri","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/newsupri.png"},
  {"id":"292","name":"Noortek","description":"Ferramenta da Noortek para cadastro de candidatos e controle das atividades quando estes forem contratados para um projeto.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/noortek.png"},
  {"id":"213","name":"Norcola","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/norcola.png"},
  {"id":"214","name":"Nordest","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"59","name":"Nordeste Import","description":"Site da empresa com divulga\u00e7\u00e3o dos ve\u00edculos dispon\u00edveis","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/nordesteImport.png"},
  {"id":"217","name":"Nossa Feira","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"218","name":"Novacape","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"221","name":"O Galo da Madrugada","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/ogaloMadrugada.png"},
  {"id":"293","name":"O Porto Restaurante e Caf\u00e9","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/oporto.png"},
  {"id":"219","name":"Odara","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"301","name":"Oficina Corporativa","description":"Site da empresa, com banco de dados e ZaitePronto","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/oficinacorporativa.png"},
  {"id":"220","name":"Oficina do Papel","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/oficinaPapel.png"},
  {"id":"60","name":"Olha Recife","description":"Site apresentando os passeios dispon\u00edveis com possibilidade de inscri\u00e7\u00e3o.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/olharecife.png"},
  {"id":"222","name":"Onix Sleep Center","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"340","name":"Opine Aqui","description":"Aplicativo para cria\u00e7\u00e3o de pesquisas","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/opineAqui.png"},
  {"id":"223","name":"Optimidia","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"37","name":"Orquestra Crian\u00e7a Cidad\u00e3","description":"Site do projeto Orquestra Crian\u00e7a Cidad\u00e3 com informa\u00e7\u00f5es diversas sobre o projeto, a equipe, not\u00edcias relacionadas e calend\u00e1rio de eventos.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/occ.png"},
  {"id":"224","name":"Oswaldo Cruz","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"225","name":"Overlay","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"226","name":"Padaria La Roque","description":"Site institucional, com informa\u00e7\u00f5es dos produtos e servi\u00e7os. H\u00e1 tamb\u00e9m periodicamente promo\u00e7\u00f5es integradas a fanpage.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/padariaLaroque.png"},
  {"id":"358","name":"Par\u00f3quia Cristo Redentor","description":"Site da par\u00f3quia localizada nos bairros de Jord\u00e3o e Ibura","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/paroquiaCristoRedentor.png"},
  {"id":"67","name":"Pascoal Im\u00f3veis","description":"Corretora de Im\u00f3veis","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/pascoal.png"},
  {"id":"295","name":"Patricia Mattos","description":"Site com divulga\u00e7\u00e3o dos servi\u00e7os da empresa, tamb\u00e9m focado para dicas de vida saud\u00e1vel.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/patMattos.png"},
  {"id":"227","name":"PDHC","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/pdhc.png"},
  {"id":"38","name":"Pernambucred","description":"Site institucional, onde suas pe\u00e7as devem estar de acordo com o manual de comunica\u00e7\u00e3o fornecido pela Unicred.\nO site atual \u00e9 uma vers\u00e3o de site para \"singular\" apresentada no Manual Unicred, por\u00e9m, com alguns ajustes. Ainda assim, \u00e9 importante se ater ao repert\u00f3rio visual oferecido pela Unicred.\nEntretanto o Manual foi alterado. Temos ent\u00e3o que promover essa altera\u00e7\u00e3o no layout do site.\nH\u00e1 ainda ferramentas como Sobras, Cupons e \u201cvendedor\u201d.\n\u00c9 acompanhada pela ag\u00eancia de publicidade USI+, e as pe\u00e7as devem estar de acordo com os crit\u00e9rios estabelecidos por ela.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/pernambucred.png"},
  {"id":"298","name":"Pernambucred","description":"Sistema que registra e controla os atendimentos realizados pela Pernambucred.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"228","name":"Phoenix","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/phoenix.png"},
  {"id":"229","name":"Phonect","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"230","name":"Pietro Miranda","description":"Site da empresa locadora de m\u00f3veis para eventos.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/pietroMiranda.png"},
  {"id":"231","name":"Pinzon","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"232","name":"Pitbull","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"233","name":"Planus","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/planus.png"},
  {"id":"234","name":"Plugnet","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/plugnet.png"},
  {"id":"62","name":"Porcelanarte","description":"Site divulgando a artista e seus produtos","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/porcelanarte.png"},
  {"id":"39","name":"Portal das Associa\u00e7\u00f5es","description":"Portal com informa\u00e7\u00f5es das associa\u00e7\u00f5es. Sistema com cadastro das pessoas associadas \u00e0s associa\u00e7\u00f5es.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/portal.png"},
  {"id":"235","name":"Portalne","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"307","name":"P\u00f3rtico Esquadrias","description":"Site da empresa, com banco de dados e ZaitePronto","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/porticoesquadrias.png"},
  {"id":"236","name":"Porto Digital - Farol","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/Portodigital.png"},
  {"id":"237","name":"Pousada Solar dos Ventos","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/pousadaSolardosventos.png"},
  {"id":"238","name":"Praxar","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"239","name":"Precatorios","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"74","name":"Premier C\u00e2mbio ","description":"Site da empresa com informa\u00e7\u00f5es institucionais sobre a empresa, seus servi\u00e7os, legisla\u00e7\u00e3o e normas, e not\u00edcias. Tamb\u00e9m h\u00e1 um sistema que registra as opera\u00e7\u00f5es (c\u00e2mbio) realizadas pela empresa.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/premier.png"},
  {"id":"240","name":"Prisma","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/prisma.png"},
  {"id":"241","name":"Procenge - Cyberartes","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/procenge.png"},
  {"id":"40","name":"Prodieta","description":"Site institucional com os produtos e servi\u00e7os oferecidos. H\u00e1 tamb\u00e9m um sistema para registro e controle dos atendimentos.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/prodieta.png"},
  {"id":"242","name":"Projectus","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/projectus.png"},
  {"id":"243","name":"Projest Constru\u00e7\u00f5es","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/projest.png"},
  {"id":"296","name":"Pronto Tecnologia","description":"Site da empresa, com banco de dados e ZaitePronto","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/prontotecnologia.png"},
  {"id":"302","name":"Pronto Tecnologia","description":"Desenvolver um sistema para as construtoras e seus corretores registrarem e controlarem os atendimentos feitos aos clientes e pessoas interessadas.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"244","name":"Propeq","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/propeq.png"},
  {"id":"245","name":"QQWW","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"9","name":"Qualim\u00e9trica","description":"Site sobre a Qualim\u00e9trica","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/logo_qualimetrica.png"},
  {"id":"246","name":"Quality Enxovais","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"256","name":"R\u00e1dio Cidade","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/radiodacidade.png"},
  {"id":"247","name":"Ranulpho","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/ranulpho.png"},
  {"id":"248","name":"Red Lounge","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/red.png"},
  {"id":"376","name":"Reis Advocacia","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"249","name":"Remult","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"250","name":"Renato Motos","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"251","name":"Roccia Constru\u00e7\u00f5es","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/roccia.png"},
  {"id":"291","name":"Rodomake","description":"Site institucional da empresa","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/rodomake.png"},
  {"id":"252","name":"Romarco","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/romarco.png"},
  {"id":"253","name":"Salvador Shopping","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"254","name":"Sa\u00fade Excelsior","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/excelsiorsaud.png"},
  {"id":"255","name":"Sbacv","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"257","name":"Sebasti\u00e3o","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"258","name":"SEC","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"259","name":"Sec Adm","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"260","name":"Sec Def Social","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"261","name":"Sec Saude","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"41","name":"SECOVI","description":"Site institucional, com informa\u00e7\u00f5es da entidade, seus associados, servi\u00e7os, not\u00edcias e arquivos.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/secovi.png"},
  {"id":"382","name":"Sellout ","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/logo_Sellout.png"},
  {"id":"262","name":"Senior","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"366","name":"Sert\u00e3o Mais","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/sertaomais.png"},
  {"id":"263","name":"SESC-PE","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/sesc.png"},
  {"id":"264","name":"Sescoop","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/sescoop.png"},
  {"id":"265","name":"SGT","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"266","name":"Sibrasa","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/sibrasa.png"},
  {"id":"45","name":"Sicredi Bel\u00e9m","description":"Site institucional. Diferentemente da Pernambucred, o layout n\u00e3o ficou atrelado ao manual de comunica\u00e7\u00e3o fornecido pela Unicred.\nH\u00e1 ainda ferramentas como Sobras e Cupons.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/sicredibelem.png"},
  {"id":"328","name":"Sicredi Cear\u00e1","description":"Sistema para gest\u00e3o dos atendimentos realizados pela empresa","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/sicrediceara.png"},
  {"id":"42","name":"Signo Comunica\u00e7\u00e3o","description":"Site institucional, com not\u00edcias da empresa e de seus clientes. Atividades de cria\u00e7\u00e3o para este cliente s\u00e3o bem raras. H\u00e1 uma ferramenta de acompanhamento de atividades bastante utilizada pela empresa.\n--\nO novo site \u00e9 institucional e simples. O layout vir\u00e1 pronto, a Zaite foi respons\u00e1vel pela implementa\u00e7\u00e3o.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/signo.png"},
  {"id":"267","name":"Simples Telecom","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/simples.png"},
  {"id":"43","name":"Sindicombust\u00edveis","description":"O site \u00e9 um portal de not\u00edcias aos associados e cont\u00e9m informa\u00e7\u00f5es e documentos para os interessados da \u00e1rea. ","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/sindicombustiveis.png"},
  {"id":"268","name":"Sindojepe","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"44","name":"Sinduscon","description":"O site \u00e9 um portal de not\u00edcias aos associados do sindicato, e cont\u00e9m informa\u00e7\u00f5es aos que buscam interesse. ","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/sinduscon.png"},
  {"id":"269","name":"Sindusgesso","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"270","name":"Sociedade DST","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"323","name":"Solar Cedro","description":"O site traz informa\u00e7\u00f5es institucionais, com divulga\u00e7\u00e3o de servi\u00e7os, leil\u00f5es, legisla\u00e7\u00e3o e not\u00edcias.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/trader_solarCedro.png"},
  {"id":"271","name":"Soservi","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"341","name":"Spa do Piso","description":"Site Institucional com informa\u00e7\u00f5es da empresa, servi\u00e7os e produtos","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/spadopiso.png"},
  {"id":"272","name":"SPLA","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"10","name":"SPPE","description":"O site funciona como um canal de not\u00edcias para jornalistas e a sociedade.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/sppe.png"},
  {"id":"273","name":"SQS Qualidade","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/SQS.png"},
  {"id":"370","name":"Statera Cursos","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/statera.png"},
  {"id":"274","name":"Super Van Azul","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"313","name":"Supermercado Lagoa","description":"Site do supermercado","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/logo_lagoa.png"},
  {"id":"312","name":"Tadeu Alencar","description":"Site do pol\u00edtico, com banco de dados e ZaitePronto","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"275","name":"Tecelagem Sao Jos\u00e9","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"276","name":"Tempest","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/tempest.png"},
  {"id":"386","name":"Think 834","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/Think.jpg"},
  {"id":"277","name":"TMO","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"362","name":"Tolentino Engenharia","description":"Site da empresa que vende e loca empilhadeiras","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/tolentino.png"},
  {"id":"308","name":"Top Of Mind - PE (FCAP JR)","description":"Site do evento, com banco de dados e ZaitePronto","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/topofmind.png"},
  {"id":"19","name":"Trader Energia","description":"O site traz informa\u00e7\u00f5es institucionais, com divulga\u00e7\u00e3o de servi\u00e7os, leil\u00f5es, legisla\u00e7\u00e3o e not\u00edcias.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/trader.png"},
  {"id":"316","name":"Trader USA","description":"O site traz informa\u00e7\u00f5es sobre a atua\u00e7\u00e3o da empresa nos Estados unidos. Tr\u00e1s as informa\u00e7\u00f5es da empresa e seus servi\u00e7os. ","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/traderUSA.png"},
  {"id":"278","name":"Unieco","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"63","name":"Unika Servi\u00e7os","description":"Site institucional com informa\u00e7\u00f5es da empresa, seus servi\u00e7os e not\u00edcias. Mant\u00e9m o foco na divulga\u00e7\u00e3o de vagas de empregos dispon\u00edveis.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/unika.png"},
  {"id":"351","name":"Universidade UVA","description":"Hotsite onde o estudante preencher\u00e1 um formul\u00e1rio para obter desconto nas mensalidades da faculdade.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/faculdadeUva.png"},
  {"id":"279","name":"Up To Date","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/up.png"},
  {"id":"368","name":"Urban Hub","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/urbanhub.png"},
  {"id":"280","name":"Usi Mais Comunica\u00e7\u00e3o","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/usimais.png"},
  {"id":"64","name":"V1 Blindados","description":"Site da empresa com divulga\u00e7\u00e3o dos ve\u00edculos dispon\u00edveis","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/v1blindados.png"},
  {"id":"281","name":"Vanguard","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/vanguard.png"},
  {"id":"282","name":"Vestibular FBV","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"284","name":"Via Sul Repasse","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"26","name":"Via Sul Ve\u00edculos","description":"Site da concession\u00e1ria, com disposi\u00e7\u00e3o dos ve\u00edculos dispon\u00edveis, promo\u00e7\u00f5es e servi\u00e7os. H\u00e1 tamb\u00e9m as vers\u00f5es para o face e para mobile.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/grupo_vs_viaSul.png"},
  {"id":"388","name":"Via Tr\u00e2nsito","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/Viatransito.jpg"},
  {"id":"283","name":"Vias Sorts","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"285","name":"Victor Camaroti","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"287","name":"Vokswagen NE","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"286","name":"V\u00f3rtice","description":null,"brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"46","name":"WCA Interc\u00e2mbios","description":"Site institucional, com muitas informa\u00e7\u00f5es sobre os cursos e escolas no exterior. H\u00e1 uma ferramenta de or\u00e7amento on-line bastante utilizada pelos internautas e pela empresa.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/wca.png"},
  {"id":"288","name":"WPD Tecnologia","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/wpd.png"},
  {"id":"331","name":"www.cacimbanoronha.com","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"332","name":"www.varandanoronha.com","description":"","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"329","name":"You Brazil","description":"Site (loja) da You Brazil","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"73","name":"Zaite Tecnologia","description":"Especializada no desenvolvimento de sites e sistemas.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/"},
  {"id":"65","name":"Zulemar Im\u00f3veis","description":"Site da empresa com divulga\u00e7\u00e3o dos im\u00f3veis dispon\u00edveis","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/zulemar.png"},
  {"id":"47","name":"Zygmunt Katz","description":"Site institucional, com not\u00edcias da \u00e1rea e informa\u00e7\u00f5es dos im\u00f3veis dispon\u00edveis para loca\u00e7\u00e3o.","brand":"https:\/\/zaite.com.br\/arqConteudo\/arqProjetos\/zykatz.png"}
  ]);
  const [clientesSelecionados, setClientesSelecionados] = React.useState([
    "Nautico", "Facho ", "Colégio Santa Maria", "ASSERPE","AABB Recife","Saúde Excelsior", "SECOVI", "Natural da Vaca", "Sindicombustíveis", "Game Station"
  ])  
  return (
    <div className="imagens">{clients && clients.map((client) => (
      clientesSelecionados.map((cS) => (
          client.name === cS?<img src={client.brand.replace("https", "http")} className="imgCliente" title={client.name}/>:null
      ))
  ))}
  </div>
  );
}

export default App;
